# https://github.com/coreos/etcd
[[constraint]]
  name = "github.com/coreos/etcd"
  revision = "15bfc1b36162805e8a90ae747d955667870c2f95"

# https://github.com/dustin/go-humanize
[[constraint]]
  name = "github.com/dustin/go-humanize"
  revision = "bb3d318650d48840a39aa21a027c6630e198e626"

# https://github.com/fatih/color
[[constraint]]
  name = "github.com/fatih/color"
  revision = "5df930a27be2502f99b292b7cc09ebad4d0891f4"

# https://github.com/gyuho/dataframe
[[constraint]]
  name = "github.com/gyuho/dataframe"
  revision = "008fc241adc41d4bd5c54b9f6564ef16407c030e"

# https://github.com/kr/pty
[[constraint]]
  name = "github.com/kr/pty"
  revision = "95d05c1eef33a45bd58676b6ce28d105839b8d0b"

# https://github.com/olekukonko/tablewriter
[[constraint]]
  name = "github.com/olekukonko/tablewriter"
  revision = "a7a4c189eb47ed33ce7b35f2880070a0c82a67d4"

# https://github.com/spf13/cobra
[[constraint]]
  name = "github.com/spf13/cobra"
  revision = "1be1d2841c773c01bee8289f55f7463b6e2c2539"

# https://gopkg.in/yaml.v2
[[constraint]]
  name = "gopkg.in/yaml.v2"
  revision = "287cf08546ab5e7e37d55a84f7ed3fd1db036de5"
